# Generated by Django 5.0.2 on 2024-02-24 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='task',
            field=models.CharField(max_length=1000),
        ),
    ]
